name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install dependencies
        run: |
          R -e "install.packages(c('shiny', 'rsconnect', 'plotly', 'readr', 'dplyr'), dependencies = TRUE)"

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          R -e "rsconnect::setAccountInfo(name='crismmdv', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
          R -e "rsconnect::deployApp(appDir = '.', appName = '${{ secrets.SHINYAPPS_NAME }}')"
