name: Deploy Shiny App2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install rsconnect-python
        run: |
          pip install rsconnect-python

      - name: Deploy to shinyapps.io
        run: |
          rsconnect configure --token $SHINYAPPS_TOKEN --secret $SHINYAPPS_SECRET
          rsconnect deploy shiny . --name $SHINYAPPS_NAME --title "Mi Aplicación Shiny"
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
